version: '3.5'

services:
  rabbitmq:
    image: docker.io/bitnami/rabbitmq:3.13
    ports:
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_LOGS=-
    volumes:
      - './data/rabbitmq_data:/bitnami/rabbitmq/mnesia'