version: "3"

services:
  gitea-mysql:
    image: docker.repo.swifer.co/bitnami/mysql:8.4
    container_name: gitea-mysql
    volumes:
      - ./data/mysql_data:/bitnami/mysql/data
    networks:
      - gitea
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=Koala123
      - MYSQL_USER=koala
      - MYSQL_PASSWORD=Koala123
      - MYSQL_DATABASE=gitea
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh' ]
      interval: 15s
      timeout: 5s
      retries: 6
  gitea:
    container_name: gitea
    image: gitea/gitea:1.22.1-rootless
    restart: always
    networks:
      - gitea
    volumes:
      - ./data/data:/var/lib/gitea
      - ./data/config:/etc/gitea
    ports:
      - "3000:3000"
      - "2222:2222"
networks:
  gitea:
    driver: bridge