# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '3.5'
services:
  stats:
    image: docker.io/bitnami/rabbitmq:3.13
    environment:
      - RABBITMQ_NODE_TYPE=stats
      - RABBITMQ_NODE_NAME=rabbit@stats
      - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_LOGS=-
    ports:
      - '15672:15672'
    volumes:
      - './data/rabbitmq_data:/bitnami/rabbitmq/mnesia'
  queue-disc1:
    image: docker.io/bitnami/rabbitmq:3.13
    environment:
      - RABBITMQ_NODE_TYPE=queue-disc
      - RABBITMQ_NODE_NAME=rabbit@queue-disc1
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@stats
      - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_LOGS=-
    volumes:
      - './data/rabbitmq_data:/bitnami/rabbitmq/mnesia'
  queue-ram1:
    image: docker.io/bitnami/rabbitmq:3.13
    environment:
      - RABBITMQ_NODE_TYPE=queue-ram
      - RABBITMQ_NODE_NAME=rabbit@queue-ram1
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@stats
      - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_LOGS=-
    volumes:
      - './data/rabbitmq_data:/bitnami/rabbitmq/mnesia'