apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  # Specify a name
  name: spinnaker-secret-generator
  # namespace: spinnaker
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - ./files-patch.enc.yaml