apiVersion: spinnaker.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  # spec.spinnakerConfig - This section is how to specify configuration spinnaker
  spinnakerConfig:
    # spec.spinnakerConfig.service-settings - This section contains the YAML of the service's service-setting
    # see https://www.spinnaker.io/reference/halyard/custom/#tweakable-service-settings for available settings
    service-settings:
      spinnaker:
        kubernetes.useExecHealthCheck: false
      clouddriver: 
        artifactId: docker.repo.swifer.co/spinnaker-community/clouddriver:5.85.2
      deck:
        artifactId: docker.repo.swifer.co/spinnaker-community/deck:3.17.0
      echo: 
        artifactId: docker.repo.swifer.co/spinnaker-community/echo:2.41.0
      fiat: 
        artifactId: docker.repo.swifer.co/spinnaker-community/fiat:1.46.0
      front50: 
        artifactId: docker.repo.swifer.co/spinnaker-community/front50:2.32.0
      gate: 
        artifactId: docker.repo.swifer.co/spinnaker-community/gate:6.62.0
      igor: 
        artifactId: docker.repo.swifer.co/spinnaker-community/igor:4.16.0
      kayenta:
        artifactId: docker.repo.swifer.co/spinnaker-community/igor:2.40.0
      orca: 
        artifactId: docker.repo.swifer.co/spinnaker-community/orca:8.51.0
      rosco:
        artifactId: docker.repo.swifer.co/spinnaker-community/rosco:1.20.1
      redis:
        artifactId: docker.repo.swifer.co/spinnaker-community/redis-cluster:v2
