version: '3'

services:
  1panel:
    image: moelin/1panel:latest
    container_name: 1panel
    restart: always
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/1panel:/var/lib/docker/volumes
      - /opt/1panel:/opt
      - /root:/root
    environment:
      - TZ=Asia/Shanghai