version: '3'
services:
  1panel:
    image: moelin/1panel:v2
    container_name: 1panel
    restart: always
    ports:
      - "10086:10086"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/1panel:/var/lib/docker/volumes
      - /opt:/opt
      - /root:/root
    environment:
      - TZ=Asia/Shanghai
      - PORT=10086
      - USERNAME=1panel
      - PASSWORD=1panel_password
      - ENTRANCE=entrance
      - BASE_DIR=/opt
    labels:
      createdBy: "Apps"