version: '3.3'

services:
  shardingsphere-proxy:
    image: apache/shardingsphere-proxy:5.5.1
    container_name: shardingsphere-proxy
    volumes:
      - ./conf:/opt/shardingsphere-proxy/conf
    ports:
      - "3308:3308"
    environment:
      - PORT=3308