version: "3"

services:
  midjourney:
    image: licoy/chatgpt-midjourney:v3.3.1
    container_name: midjourney
    ports:
      - "4000:3000"
    environment:
      OPENAI_API_KEY: "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      BASE_URL: "https://api.openai.com"
      MJ_PROXY_URL: "https://ai.trueai.org/mj"
      MJ_PROXY_TOKEN: ""