version: "3.2"

services:
  stable-diffusion-webui:
    container_name: stable-diffusion-webui
    image: universonic/stable-diffusion-webui:minimal
    command: --use-cpu all --no-half --precision full --skip-torch-cuda-test
    restart: unless-stopped
    ports:
      - "8080:8080/tcp"
    volumes:
      - .data/inputs:/app/stable-diffusion-webui/inputs
      - .data/textual_inversion_templates:/app/stable-diffusion-webui/textual_inversion_templates
      - .data/embeddings:/app/stable-diffusion-webui/embeddings
      - .data/extensions:/app/stable-diffusion-webui/extensions
      - .data/models:/app/stable-diffusion-webui/models
      - .data/localizations:/app/stable-diffusion-webui/localizations
      - .data/outputs:/app/stable-diffusion-webui/outputs
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    deploy:
      mode: global
      placement:
        constraints:
          - "node.labels.iface != extern"