version: "3.5"

services:
  sonarqube:
    build: ./container
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar@2018
    volumes:
      - .data/sonarqube/data:/opt/sonarqube/data
      - .data/sonarqube/extensions:/opt/sonarqube/extensions
      - .data/sonarqube/logs:/opt/sonarqube/logs
      - .data/sonarqube/temp:/opt/sonarqube/temp
    ports:
      - "19000:9000"
    networks:
      sonarqube:
        aliases:
          - sonarqube
  db:
    image: postgres:12
    
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar@2018
    volumes:
      - ./data/sonarqube/pg:/var/lib/postgresql
      - ./data/sonarqube/pg_data:/var/lib/postgresql/data
    networks:
      sonarqube:
        aliases:
          - db
networks:
  sonarqube:
    name: sonarqube
    driver: bridge