version: '3.3'

services:
  jenkins-agent:
    image: docker.repo.swifer.co/sp_library/jenkins-agent:lts-sp
    network_mode: host
    environment:
      JENKINS_URL: http://localhost:8080
      JENKINS_SECRET: c9378760939172a7d568dcb13cc559a471a9b31c9a89dcc1cc6f4f599c1a9b1d
      JENKINS_AGENT_NAME: node1
    volumes:
      - ./data:/home/jenkins/agent