version: '3.3'

services:
  jenkins-agent:
    image: docker.repo.swifer.co/sp_library/jenkins-agent:lts-sp
    network_mode: host
    env_file:
      - ../conf/common.env
    environment:
      JENKINS_URL: http://localhost:8080
      JENKINS_SECRET: 8d373f37fc3bd647897f6247b280b9280dbed1f32d4411c4e79c56c282e7fd95
      JENKINS_AGENT_NAME: node1
    volumes:
      - ./data/agent:/home/jenkins/agent
      - ./data/workspace:/home/workspace