version: '3.3'

services:
  jenkins-agent:
    image: docker.repo.swifer.co/sp_library/jenkins-agent:lts-sp
    network_mode: host
    env_file:
      - ../conf/common.env
      - ../conf/config.env
    environment:
      JENKINS_URL: http://localhost:8080
      JENKINS_SECRET: b69a5081fdfe4f0db2763f9fd5655247c067cf57f236502e8438439793ce56f3
      JENKINS_AGENT_NAME: node1
    volumes:
      - ./data/workspace:/home/jenkins/workspace
      - ./data/agent:/home/jenkins/agent
      - ./data/repo:/home/jenkins/repo