version: '3.3'

services:
  jenkins-agent:
    image: docker.repo.swifer.co/sp_library/jenkins-agent:lts-sp
    network_mode: host
    env_file:
      - ../conf/common.env
      - ../conf/config.env
    environment:
      JENKINS_URL: http://localhost:8080
      JENKINS_SECRET: ced049eb35d1df8cdc4e597ff946d251bdffe511b998746de4464c504ed60d16
      JENKINS_AGENT_NAME: node1
    volumes:
      - ./data/workspace:/home/jenkins/workspace
      - ./data/agent:/home/jenkins/agent
      - ./data/repo:/home/jenkins/repo