# 服务器的公网ip
serverAddr = "120.76.98.51"
# 7000端口 与frps.toml一致
serverPort = 7000

[[proxies]]
# 自定义名称
name = "ollama"
# type这里写http
type = "tcp"
# 本地端口，例如本地启动的服务需要使用8000端口访问，这里就写8000
localPort = 11434
# 服务器的监听端口，与frps.toml一致
remotePort = 11433

[[proxies]]
# 自定义名称
name = "stable-diffusion-webui"
# type这里写http
type = "tcp"
# 本地端口，例如本地启动的服务需要使用8000端口访问，这里就写8000
localPort = 7860
# 服务器的监听端口，与frps.toml一致
remotePort = 7860

