services:
  db:
    image: bitnami/mysql:8.4
    container_name: xanadu-db
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_USER=wftapp
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=Xanadu
    ports:
      - "8083:3306"
    # 数据挂载
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./server/init:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh' ]
      interval: 15s
      timeout: 5s
      retries: 6
    networks:
      - docker
  backend:
    container_name: xanadu-server
    image: registry.cn-shanghai.aliyuncs.com/koala888/xanadu-server:latest
    build:
      context: ./server
    ports:
      - "8082:3000"
    depends_on:
      - db
    restart: always
    networks:
      - docker

  frontend:
    container_name: xanadu-frontend
    image: registry.cn-shanghai.aliyuncs.com/koala888/xanadu-frontend:latest
    ports:
      - "8081:80"
    build:
      context: .
    depends_on:
      - backend
    restart: always
    networks:
      - docker
networks:
  docker:
    external: true
