version: '3.3'
services:
  alist:
    image: rclone/rclone
    container_name: rclone
    volumes:
      - ./data:/config/rclone
    ports:
      - '5244:5244'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    restart: unless-stopped