version: "3"

services:
  mtphotos:
    image: mtphotos/mt-photos:latest
    container_name: mt-photos
    restart: always
    ports:
      - 8063:8063
    volumes:
      - /data/docker/mt_photos/config:/config
      - /data/mt_photos:/upload
      - /data/photos:/photos
    environment:
      - TZ=Asia/Shanghai