version: '3'

services:
  nginx:
    image: docker.io/bitnami/nginx:1.25
    container_name: nginx
    ports:
      - '80:8080'
    volumes:
      - type: bind
        source: ./conf/server_blocks
        target: /opt/bitnami/nginx/conf/server_blocks
      - type: bind
        source: ./html
        target: /app/html
    networks:
      - docker
networks:
  docker:
    external: true