version: '3'

services:
  nginx:
    image: docker.io/bitnami/nginx:1.25
    container_name: nginx
    ports:
      - '8080:8080'
    volumes:
      - type: bind
        source: ./conf/server_blocks
        target: /opt/bitnami/nginx/conf/server_blocks