version: '3.3'
services:
  pg:
    image: ankane/pgvector:v0.5.0 # git
    container_name: pg
    restart: always
    ports:
      - "5432:5432"
    networks:
      - fast
    environment:
      - POSTGRES_USER=fastGpt
      - POSTGRES_PASSWORD=fastGpt
      - POSTGRES_DB=postgres
    volumes:
      - /e/data/fastGpt/postgresql:/var/lib/postgresql/data
  mongo:
    image: mongo:5.0.18
    container_name: mongo
    restart: always
    ports: # 生产环境建议不要暴露
      - "27017:27017"
    networks:
      - fast
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fastGpt
      - MONGO_INITDB_ROOT_PASSWORD=fastGpt
    volumes:
      - /e/data/fastGpt/mongo/data:/data/db
  fast:
    container_name: fast
    image: ghcr.io/labring/fastgpt:latest
    ports:
      - "3000:3000"
    networks:
      - fast
    depends_on:
      - mongo
      - pg
    restart: always
    environment:
      # root 密码，用户名为: root
      - DEFAULT_ROOT_PSW=1234
      # 中转地址，如果是用官方号，不需要管。务必加 /v1
      - OPENAI_BASE_URL=https://api.openai.com/v1
      - CHAT_API_KEY=sk-xxxx
      - DB_MAX_LINK=5 # database max link
      - TOKEN_KEY=any
      - ROOT_KEY=root_key
      - FILE_TOKEN_KEY=filetoken
      # mongo 配置，不需要改. 如果连不上，可能需要去掉 ?authSource=admin
      - MONGODB_URI=mongodb://fastGpt:fastGpt@mongo:27017/fastgpt?authSource=admin
      # pg配置. 不需要改
      - PG_URL=postgresql://fastGpt:fastGpt@pg:5432/postgres
    volumes:
      - ./config.json:/app/data/config.json
networks:
  fast: