version: '3.8'
services:
  comfyui:
    image: yanwk/comfyui-boot:cu121
    container_name: comfyui
    ports:
      - "8188:8188"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]