version: '3.3'

services:
  mysql:
    image: docker.repo.swifer.co/bitnami/mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - './data:/bitnami/mysql/data'
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=wftapp
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=maple-edu
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh' ]
      interval: 15s
      timeout: 5s
      retries: 6