version: '3.3'
services:
  alist:
    image: 'xhofe/alist:main'
    container_name: alist
    volumes:
      - ./data:/opt/alist/data
      - /data/cloud:/data/cloud
    ports:
      - '5244:5244'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    restart: unless-stopped