version: '3'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - '11434:11434'
    volumes:
      - ./data:/root/.ollama
    restart: always
    networks:
      - docker
networks:
  docker:
    external: true