apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinnaker-operator
  namespace: spinnaker
spec:
  template:
    spec:
      containers:
        - name: spinnaker-operator
          image: docker.repo.swifer.co/armory/spinnaker-operator:1.3.1
        - name: halyard
          image: docker.repo.swifer.co/armory/halyard:operator-a6ac1d4
