version: "3"

services:
  memos:
    #image: neosmemo/memos:stable
    image: registry.cn-shanghai.aliyuncs.com/koala888/tools:memos-0.23.0-rc.1
    container_name: memos
    restart: always
    ports:
      - "5230:5230"
    volumes:
      - ./data/memos:/var/opt/memos