version: "3"

services:
  memos:
    image: registry.cn-shanghai.aliyuncs.com/koala888/tools:memos
    container_name: memos
    restart: always
    ports:
      - "5230:5230"
    volumes:
      - ./data/memos:/var/opt/memos