version: '3.3'

services:
  jenkins:
    image: docker.repo.swifer.co/sp_library/jenkins:lts-sp
    networks:
      - jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    env_file:
      - ./conf/config.env
      - ../conf/common.env
    volumes:
      - ./data/agent:/var/jenkins_home
      - ./data/workspace:/home/jenkins/workspace
      - ./init.groovy.d:/usr/share/jenkins/ref/init.groovy.d
networks:
  jenkins:
    driver: bridge